# hash:sha256:69c8ae840cc42d3aef0c28646b9b7b4d2ca8c359aa0842eafd8a01082bcad6df
FROM registry.acmecorp-edge.codeocean.com/codeocean/jupyterlab:2.1.1-miniconda4.8.2-python3.8-ubuntu18.04

ARG DEBIAN_FRONTEND=noninteractive
